frontend/main/forms/cambiar_contraseña_form.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, SubmitField, StringField
from wtforms.fields.html5 import EmailField
from wtforms import validators


class ModificarDatosForm(FlaskForm):
    password = PasswordField('Password', [
        validators.Required(),
        validators.EqualTo('confirm', message='Las contraseñas no coinciden')
    ])

    confirm = PasswordField('Repita la contraseña')
    submit = SubmitField("Cambiar contraseña")

frontend/main/routes/admin.py
import json
import requests
from flask import Blueprint, render_template, redirect, url_for, current_app, request, flash
from flask_login import login_required, LoginManager, current_user
from ..forms.agregar_bolson_form import BolsonForms
from .auth import admin_required, proveedor_required
from ..forms.modificar_datos_form import ModificarDatosForm
from ..forms.agregar_proveedor_form import AgregarProveedorForm, FormFilterProveedor
from ..forms.agregar_bolson_form import BolsonForms, FormFilterBolsones, FormFilterBolson
from ..forms.registrarse_form import RegistrarseForm
from ..forms.producto_form import FormFilterProducto

admin = Blueprint('admin', __name__, url_prefix='/admin')


@admin.route('/cuenta')
@login_required
@admin_required
def panel_admin():
    return render_template('panel_admin.html')


@admin.route('/consultar-compras')
@login_required
def consultar_compras():
    user = current_user
    auth = request.cookies['access_token']
    headers = {'content-type': 'application/json',
               'authorization': 'Bearer' + auth}
    r = requests.get(
        current_app.config["API_URL"] + '/bolsonesventa',
        headers=headers,
        json={}
    )
    bolsones = json.loads(r.text)["bolsonesventa"]
    return render_template('compras_admin.html', bolsones=bolsones, user=user)


@admin.route('/lista-proveedores')
@login_required
def lista_proveedores():
    filter = FormFilterProveedor(request.args, meta={'csrf': False})
    data = {}
    data["page"] = 1
    data["per_page"] = 5
    if 'page' in request.args:
        data['page'] = request.args.get('page', '')
    auth = request.cookies['access_token']
    headers = {'content-type': "application/json",
               'authorization': 'Bearer' + auth}
    if filter.submit():
        if filter.ordenamiento.data is not None:
            data['ordenamiento'] = filter.ordenamiento.data
    r = requests.get(
        current_app.config["API_URL"] + '/proveedores',
        headers=headers,
        data=json.dumps(data))
    proveedores = json.loads(r.text)["proveedores"]
    pagination = {}
    pagination["pages"] = json.loads(r.text)["pages"]
    pagination["current_page"] = json.loads(r.text)["page"]
    return render_template('lista_proveedores.html', proveedores=proveedores, pagination=pagination, filter=filter)


@admin.route('/agregar-bolson', methods=['POST', 'GET'])
@login_required
@admin_required
def agregar_bolson():
    form = BolsonForms()
    data = {
        'per_page': 10
    }
    auth = request.cookies['access_token']
    headers = {'content-type': 'application/json',
               'authorization': "Bearer" + auth}
    r = requests.get(f'{current_app.config["API_URL"]}/productos', headers={"content-type": "application/json"},
                     json=data)
    productos = json.loads(r.text)["productos"]

    productos = [(producto['id'], producto['nombre']) for producto in productos]
    productos.insert(0, (0, '--Seleccionar producto'))
    form.producto.choices = productos
    form.producto2.choices = productos
    form.producto3.choices = productos
    form.producto4.choices = productos
    if form.validate_on_submit():
        print('ENTRA')
        bolson = {
            'nombre': form.nombre.data,
            'aprobado': 1,
            'descripcion': form.descripcion.data,
            'precio': form.precio.data
        }
        r = requests.post(current_app.config["API_URL"] + '/bolsonespendientes',
                          headers=headers,
                          data=json.dumps(bolson))

        bolsonId = json.loads(r.text)['id']

        productos = [form.producto.data, form.producto2.data, form.producto3.data, form.producto4.data]
        for producto in productos:
            if producto != 0:
                print('it works')
                data = {
                    'productoId': producto,
                    'bolsonId': int(bolsonId)
                }
                r = requests.post(current_app.config["API_URL"] + '/productos-bolsones',
                                  headers=headers,
                                  data=json.dumps(data))
            else:
                print('it doesnt work')
        flash('El bolson fue agregado con exito', 'success')
        return render_template('agregar_bolson.html', form=form)
    else:
        print('no entra')
    return render_template('agregar_bolson.html', form=form)


@admin.route('/agregar-proveedor', methods=['POST', 'GET'])
@login_required
def agregar_proveedor():
    form = AgregarProveedorForm()
    if form.validate_on_submit():
        data = {"nombre": form.nombre.data, "apellido": form.apellido.data, "email": form.email.data,
                "password": form.password.data, "role": "proveedor"}
        headers = {
            'content-type': "application/json"
        }
        r = requests.post(
            current_app.config["API_URL"] + '/auth/register',
            headers=headers,
            data=json.dumps(data))
        if r.status_code == 200:
            flash('El proveedor fue creado con exito', 'success')
        if r.status_code == 409:
            flash('El mail ya fue registrado', 'warning')
    return render_template('agregar_proveedor.html', form=form)


@admin.route('/eliminar-proveedor/<int:id>')
@login_required
@admin_required
def eliminar_proveedor(id):
    auth = request.cookies['access_token']
    headers = {'content-type': "application/json",
               'authorization': "Bearer " + auth}
    r = requests.delete(current_app.config['API_URL'] + '/proveedor/' + str(id),
                        headers=headers)
    if r.status_code == 404:
        flash('El proveedor no existe', 'danger')
        return render_template('lista_proveedores.html')
    if r.status_code == 204:
        flash('El proveedor ha sido eliminado', 'success')
        return render_template('lista_proveedores.html')


@admin.route('/editar-perfil/<int:id>', methods=['POST', 'GET'])
@login_required
def editar_perfil(id):
    auth = request.cookies['access_token']
    form = ModificarDatosForm()
    usuario = {
        "nombre": form.nombre.data,
        "apellido": form.apellido.data,
        "telefono": form.telefono.data,
        "password": form.password.data
    }

    r = requests.put(current_app.config['API_URL'] + '/cliente/' + str(id),
                     headers={'content-type': "application/json",
                              'authorization': "Bearer " + auth},
                     json=usuario
                     )
    return render_template('editar_perfil.html', form=form, id=id)


@admin.route('/bolsones')
@login_required
@admin_required
def ver_todos():
    user = current_user
    filter = FormFilterBolsones(request.args, meta={'csrf': False})
    auth = request.cookies['access_token']
    headers = {'content-type': 'application/json',
               'authorization': "Bearer" + auth}
    data = {}
    data['page'] = 1
    data['per_page'] = 5
    if 'page' in request.args:
        data['page'] = request.args.get('page', '')
    if filter.submit():
        if filter.desde.data is not None:
            data['desde'] = filter.desde.data.strftime('%Y-%m-%d')
        if filter.hasta.data is not None:
            data['hasta'] = filter.hasta.data.strftime('%Y-%m-%d')
    r = requests.get(current_app.config['API_URL'] + '/bolsones',
                     headers=headers,
                     data=json.dumps(data))
    bolsones = json.loads(r.text)["bolsones"]
    pagination = {}
    pagination["pages"] = json.loads(r.text)["pages"]
    pagination["current_page"] = json.loads(r.text)["page"]
    return render_template('bolsones_admin.html', pagination=pagination, bolsones=bolsones, filter=filter, user=user)


@admin.route('/ver-productos')
def ver_productos():
    form = FormFilterProducto(request.args, meta={'csrf': False})
    auth = request.cookies['access_token']
    headers = {'content-type': 'application/json',
               'authorization': "Bearer" + auth}
    data = {}
    data['page'] = 1
    data['per_page'] = 10
    if 'page' in request.args:
        data['page'] = request.args.get('page', '')
    r = requests.get(
        current_app.config['API_URL'] + '/proveedores',
        headers=headers,
        data=json.dumps(data))
    proveedores = json.loads(r.text)["proveedores"]
    proveedores = [(proveedor['id'], f'{proveedor["nombre"]} {proveedor["apellido"]}') for proveedor in proveedores]
    proveedores.insert(0, (0, 'Seleccionar proveedor'))
    form.proveedor.choices = proveedores
    if form.submit():
        if form.proveedor.data is not None and form.proveedor.data != 0:
            data["usuarioId"] = int(form.proveedor.data)
    r = requests.get(current_app.config['API_URL'] + '/productos',
                     headers=headers,
                     data=json.dumps(data))
    productos = json.loads(r.text)["productos"]
    pagination = {}
    pagination["pages"] = json.loads(r.text)["pages"]
    pagination["current_page"] = json.loads(r.text)["page"]
    return render_template('ver_productos.html', productos=productos, pagination=pagination, form=form,
                           proveedores=proveedores)


@admin.route('/producto-eliminar/<int:id>')
def eliminar_producto(id):
    auth = request.cookies['access_token']
    r = requests.delete(f'{current_app.config["API_URL"]}/producto/{id}',
                        headers={'content-type': "application/json",
                                 'authorization': "Bearer " + auth})
    return redirect(url_for('admin.ver_productos'))


@admin.route('/compras')
def ver_compras():
    data = {}
    data['page'] = 1
    data['per_page'] = 3
    auth = request.cookies['access_token']
    headers = {"content-type": "applications/json",
               'authorization': "Bearer " + auth}
    r = requests.get(current_app.config['API_URL'] + '/compras',
                     headers=headers,
                     json=data)
    compras = json.loads(r.text)["clientes"]
    pagination = {}

frontend/main/routes/inicio.py
import json
import requests
from flask import Blueprint, current_app, render_template, redirect, url_for, request

# Crear Blueprint
inicio = Blueprint('inicio', __name__, url_prefix='/inicio')


@inicio.route('/')
def index():
    # Mostrar template
    return render_template('inicio.html')


@inicio.route('/inicio-registrado')
def inicio_logeado():
    return render_template('inicio_registrado.html')


@inicio.route('/inicio-no-registrado')
def inicio_no_logeado():
    return render_template('inicio.html')

frontend/main/routes/main.py
import json
import requests
from flask import Blueprint, redirect, url_for, current_app, make_response, flash
from flask_login import login_user, logout_user

from .auth import User
from ..forms.iniciar_sesion_form import LoginForm

main = Blueprint('main', __name__, url_prefix='/')


@main.route('/')
def index():
    return redirect(url_for('inicio.index'))


@main.route('/login', methods=['POST'])
def login():
    loginForm = LoginForm()
    if loginForm.validate_on_submit():
        data = '{"email":"' + loginForm.email.data + '", "password":"' + loginForm.password.data + '"}'
        r = requests.post(
            current_app.config["API_URL"] + '/auth/login',
            headers={"content-type": "application/json"},
            data=data)
        if r.status_code == 200:
            user_data = json.loads(r.text)
            user = User(id=user_data.get("id"), email=user_data.get("email"), role=user_data.get("role"))
            login_user(user)
            req = make_response(redirect(url_for('inicio.index')))
            req.set_cookie('access_token', user_data.get("access_token"), httponly=True)
            return req
        else:
            flash('Usuario o contraseña incorrecta', 'danger')
    return redirect(url_for('inicio.index'))


@main.route('/logout')
def logout():
    req = make_response(redirect(url_for('inicio.index')))
    req.set_cookie('access_token', '', httponly=True)
    req.delete_cookie('access_token', httponly=False)
    logout_user()
    return req

frontend/main/routes/proveedor.py
import json
import requests
from flask import Blueprint, render_template, redirect, url_for, current_app, request, flash
from flask_login import login_required, LoginManager, current_user
from ..forms.modificar_datos_form import ModificarDatosForm
from ..forms.registrarse_form import RegistrarseForm
from ..forms.producto_form import AgregarProductoForms
from .auth import admin_required, proveedor_required

proveedor = Blueprint('proveedor', __name__, url_prefix='/proveedor')


@proveedor.route('/registrar', methods=['POST', 'GET'])
def registrar():
    form = RegistrarseForm
    if form.validate_on_submit():
        print(form.nombre.data)
        return redirect(url_for('main.index'))
    return render_template('agregar_proveedor.html', form=form)


@proveedor.route('/agregar-producto', methods=['POST', 'GET'])
def agregar_producto():
    form = AgregarProductoForms()
    auth = request.cookies['access_token']
    if form.validate_on_submit():
        producto = {
            "nombre": form.nombre.data,
            "usuarioid": current_user.id
        }
        r = requests.post(current_app.config["API_URL"] + '/productos',
                          headers={'content-type': "application/json",
                                   'authorization': "Bearer " + auth},
                          json=producto)
        if r.status_code == 201:
            flash("Producto creado con exito", "success")
    return render_template('modificar_producto_prov.html', form=form)


@proveedor.route('/panel-proveedor')
def panel_proveedor():
    return render_template('panel_proveedor.html')


@proveedor.route('/editar-perfil/<int:id>', methods=['POST', 'GET'])
@login_required
def editar_perfil(id):
    auth = request.cookies['access_token']
    form = ModificarDatosForm()
    usuario = {
        "nombre": form.nombre.data,
        "apellido": form.apellido.data,
        "telefono": form.telefono.data,
        "password": form.password.data
    }

    r = requests.put(current_app.config['API_URL'] + '/cliente/' + str(id),
                     headers={'content-type': "application/json",
                              'authorization': "Bearer " + auth},
                     json=usuario
                     )
    return render_template('editar_perfil.html', form=form, id=id)

frontend/main/routes/ver_bolsones.py
from .. forms.agregar_bolson_form import BolsonForms
from .. forms.compras_form import CompraForms
import json
import requests
from flask_login import login_required, LoginManager, current_user
from flask import redirect, render_template, url_for, Blueprint, current_app, request
from .auth import admin_required, proveedor_required

ver_bolsones = Blueprint('ver_bolsones', __name__, url_prefix='/ver_bolsones')


@ver_bolsones.route('/bolsones_venta')
@login_required
def bolsones_registrado():
    r = requests.get(f'{current_app.config["API_URL"]}/bolsones-venta',
                     headers={"content-type": "application/json"},)
    bolsones = json.loads(r.text)["bolsonesventa"]
    return render_template('ver_bolsones_registrado.html', bolsones=bolsones)


@ver_bolsones.route('/bolsones-sin-logear')
def ver():
    headers = {'content-type': 'application/json'}
    r = requests.get(
        current_app.config["API_URL"]+'/bolsones',
        headers=headers,
        data=json.dumps(data)
    )
    bolsones = json.loads(r.text)["bolsones"]
    return render_template('bolsones_no_logueado.html', bolsones=bolsones)


@ver_bolsones.route('/bolsones-pendientes')
@login_required
@admin_required
@proveedor_required
def bolsones_pendientes():
    user = current_user
    auth = request.cookies['access_token']
    headers = {'content-type': 'application/json',
               'authorization': "Beares"+auth}
    r = requests.get(
        current_app.config["API_URL"]+'/bolsonespendientes',
        headers=headers,
        data=json.dumps(data)
    )
    bolsones_pendientes = json.loads(r.text)["Bolsones pendientes"]
    return render_template('bolsones_pendientes.html', bolsones_pendientes=bolsones_pendientes, user=user)


@ver_bolsones.route('/bolsones-previos')
@login_required
@admin_required
@proveedor_required
def bolsones_pendientes():
    user = current_user
    auth = request.cookies['access_token']
    headers = {'content-type': 'application/json',
               'authorization': "Beares"+auth}
    r = requests.get(
        current_app.config["API_URL"]+'/bolsonesprevios',
        headers=headers,
        data=json.dumps(data)
    )
    bolsones_previos = json.loads(r.text)["Bolsones previos"]
    return render_template('bolsones_previos.html', bolsones_previos=bolsones_previos, user=user)

frontend/main/templates/agregar_bolson.html
{% extends 'main.html' %}
{% from 'macros/from_macro.html' import mostrarcampo, mostrarenvio %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static', filename='css/styles.css')}}">
{% endblock %}

{% block content %}
    <nav class="navbar navbar-expand-sm navbar-expand-md ">
      <div class="container">
             <a class="navbar-brand">Bolsoneria</a><button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
             <i class="icon ion-md-menu"></i>
             </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                     <a class="nav-link" href="{{url_for('admin.ver_todos')}}" id="listabolsones">Ver bolsones</a>
                </li>
                    <li class="nav-item">
                        <a class="nav-link btn btn-nav py-2 px-4" href="{{url_for('admin.panel_admin')}}" id="paneladmin">Panel administrador</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        <div class="alert alert-{{ messages.0.0}} text-center" role="alert">
          {% for category, message in messages %}
            {{ message }}
          {% endfor %}
        </div>
       {% endif %}
    {% endwith %}

    <div class="w3l-login-form d-flex align-items-center flex-column main-section card border-dark mb-3" style="max-width: 26rem;">
            <br><br>
        <h1><strong>Agregar bolson</strong></h1>
             <br>
        <form action="{{url_for('admin.agregar_bolson')}}" method="POST" >
            <input type="hidden" name="csrf_token" value="{{csrf_token()}}">
                <div class="w3l-login-form">
                    <div class="group">
                        {{mostrarcampo(form.nombre, class="form-control")}}
                    </div>
                    <div class="group">
                        {{mostrarcampo(form.descripcion, class="form-control")}}
                    </div>
                    <div class="group">
                        {{mostrarcampo(form.producto, class="form-control form-select input")}}
                    </div>
                    <div class="group hidden" id="producto2">
                        {{mostrarcampo(form.producto2, class="form-control form-select input", id='select2')}}
                    </div>
                    <div class="group hidden" id="producto3">
                        {{mostrarcampo(form.producto3, class="form-control form-select input", id='select3')}}
                    </div>
                    <div class="group hidden" id="producto4">
                        {{mostrarcampo(form.producto4, class="form-control form-select input", id='select4')}}
                    </div>
                    <div class="group">
                        {{mostrarcampo(form.precio, class="form-control")}}
                    </div>
                    <br>{{mostrarenvio(form.submit, class="btn button btn-xl mt-1")}}
                  <br><br>
                </div>
        </form>
    </div>


       <footer class="footer">
        <div class="container"></div>
       </footer>

{% endblock %}

frontend/main/templates/lista_proveedores.html
{% extends 'main.html' %}
{% from 'macros/from_macro.html' import mostrarcampo, mostrarenvio %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static', filename='css/styles.css')}}">
{% endblock %}

{% block content %}
    <nav class="navbar navbar-expand-sm navbar-expand-md ">
      <div class="container">
             <a class="navbar-brand">Bolsoneria</a><button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
             <i class="icon ion-md-menu"></i>
             </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                     <a class="nav-link"  href="{{url_for('cliente.panel_cliente')}}" id="usuario">{{current_user.email}}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link btn btn-primary py-2 px-4"  href="{{url_for('cliente.panel_cliente')}}" id="paneladministradoe">Panel admin</a>
                </li>
                </ul>
            </div>
        </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        <div class="alert alert-{{ messages.0.0}}" role="alert">
          {% for category, message in messages %}
            {{ message }}
          {% endfor %}
        </div>
       {% endif %}
    {% endwith %}

    <div class="row">
       <div class="col-md-12 justify-content-center">
         <form method="GET" action="{{ url_for('admin.lista_proveedores') }}" >
           <div class="form-row">
             <div class="form-group col-md-4">
             </div>
             <div class="form-group col-md-2">
                 {{ mostrarcampo(filter.ordenamiento , class='form-control')}}
             </div>
             <div class="form-group col-md-3" style="margin-top:15px">
               {{ mostrarenvio(filter.submit , class='btn btn-primary')}}
             </div>
               <div class="form-group col-md-3">
             </div>
           </div>
         </form>
       </div>
     </div>

    {% for proveedor in proveedores%}
        <div class="proveedores">
            <div class="row">
                <div class="col-sm-5 col-md-5">
                    <br>
                    <div class="section_title">Proveedor {{proveedor.id}}</div>
                </div>
                <div class="col-sm-4 col-md-4">
                    <br>
                    <div class="datos"><p>NOMBRE: {{proveedor.nombre}}</p><p>APELLIDO: {{proveedor.apellido}}</p>
                        <p>TELEFONO: {{proveedor.telefono}}</p><p>MAIL: {{proveedor.email}}</p></div>
                </div>
                <div class="col-sm-3 col-md-3">
                    <br><br>
                    <div class="datos"><p><a class="boton-secundario" href="{{url_for('admin.eliminar_proveedor', id=proveedor.id)}}">ELIMINAR</a></p></div>
                </div>
            </div>
        </div>
    {% endfor %}

    <footer class="footer">
        <div class="container">
            <div class="col-md-12">
                <br>
               <nav aria-label="Page navigation example">
                   <ul class="pagination justify-content-center" style="float:center">
                   {% if pagination.current_page != 1 %}
                   <li class="page-item">
                     <a class="page-link"
                      href="{{ url_for('admin.lista_proveedores', page = (pagination.current_page-1)) }}"
                     >Previous</a>
                   </li>
                   {% else %}
                   <li class="page-item disabled">
                     <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
                   </li>
                   {% endif %}
                   {% for n in range(1,pagination.pages+1) %}
                        {% if n != pagination.current_page %}
                             <li class="page-item">
                               <a class="page-link" href="{{ url_for('admin.lista_proveedores', page = n) }}">{{n}}</a>
                             </li>
                        {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">{{n}}</a>
                            </li>
                        {% endif %}
                   {% endfor %}
                   {% if pagination.current_page != pagination.pages %}
                   <li class="page-item">
                     <a class="page-link"
                      href="{{ url_for('admin.lista_proveedores',page = (pagination.current_page+1)) }}" >Next</a>
                   </li>
                   {% else %}
                   <li class="page-item disabled">
                     <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
                   </li>
                   {% endif %}
                 </ul>
               </nav>
         </div>
       </div>
    </footer>

{% endblock %}

frontend/main/templates/panel_admin.html
{% extends 'main.html' %}

{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static', filename='css/styles.css')}}">
{% endblock %}

{% block content %}
    <nav class="navbar navbar-expand-sm navbar-expand-md ">
      <div class="container">
             <a class="navbar-brand">Bolsoneria</a><button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
             <i class="icon ion-md-menu"></i>
             </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                         <a class="nav-link btn btn-nav py-2 px-4" href="{{url_for('inicio.inicio_logeado')}}" id="Inicio">Inicio</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="w3l-login-form d-flex align-items-center flex-column main-section">
            <h1><strong>Panel Administrador</strong></h1>
    </div>
    <div class="row">
        <div class="col-sm-4 order-sm-1 col-md-4 order-md-1 ">
            <div class="p-4 text-center">
                <a class="btn btn-primary btn-xl mt-5" style="width: 70%;" href="{{url_for('admin.editar_perfil', id=current_user['id'])}}">Editar perfil</a>
            </div>
        </div>
        <div class="col-sm-4 order-sm-1 col-md-4 order-md-1">
            <div class="p-4 text-center">
                <a class="btn btn-primary btn-xl mt-5" style="width: 70%;" href="{{url_for('admin.agregar_proveedor')}}" >Agregar proveedor</a>
            </div>
        </div>
        <div class="col-sm-4 order-sm-1 col-md-4 order-md-1">
            <div class="p-4 text-center">
                <a class="btn btn-primary btn-xl mt-5" style="width: 70%;" href="{{url_for('admin.agregar_bolson')}}">Agregar bolson</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-4 order-sm-1 col-md-4 order-md-1 ">
            <div class="p-4 text-center">
                <a class="btn btn-primary btn-xl mt-5" style="width: 70%;" href="{{url_for('admin.lista_proveedores')}}">Lista de proveedores</a>
            </div>
        </div>
        <div class="col-sm-4 order-sm-1 col-md-4 order-md-1">
            <div class="p-4 text-center">
                <a class="btn btn-primary btn-xl mt-5" style="width: 70%;" href="{{url_for('admin.ver_todos')}}">Consultar bolsones</a>
            </div>
        </div>
        <div class="col-sm-4 order-sm-1 col-md-4 order-md-1">
            <div class="p-4 text-center">
                <a class="btn btn-primary btn-xl mt-5" style="width: 70%;" href="{{url_for('admin.bolsones_pendientes')}}">Consultar bolsones pendientes</a>
            </div>
        </div>
    </div>
        <div class="row">
        <div class="col-sm-4 order-sm-1 col-md-4 order-md-1 ">
            <div class="p-4 text-center">
                <a class="btn btn-primary btn-xl mt-5" style="width: 70%;" href="{{url_for('admin.ver_productos')}}">Consultar productos</a>
            </div>
        </div>
        <div class="col-sm-4 order-sm-1 col-md-4 order-md-1">
            <div class="p-4 text-center">
                <a class="btn btn-primary btn-xl mt-5" style="width: 70%;" href="{{url_for('admin.bolsones_previos')}}">Consultar bolsones previos</a>
            </div>
        </div>
        <div class="col-sm-4 order-sm-1 col-md-4 order-md-1">
            <div class="p-4 text-center">
                <a class="btn btn-primary btn-xl mt-5" style="width: 70%;" href="{{url_for('main.logout')}}">Cerrar sesion</a>
            </div>
        </div>
    </div>



    <footer class="footer">
        <div class="container">
        </div>
    </footer>
{% endblock %}